"""The smallest add-on that satisfies the contract. Also the normalizer test double.

Generated by `addon_kit new normalizer.conformance --kind normalizer` and then given
rules. Three jobs, and it is worth being explicit that they are three:

1. **The conformance suite's subject.** It is run through every case OQ-003 lists —
   success, invalid output, retryable failure, permanent failure, version coexistence
   — so the suite is exercised against something real rather than a mock.
2. **The test double** DP-005 step 5 and OQ-003 ask for. Under an add-on model a
   double *is* an add-on, the smallest conforming one, so the category disappears
   rather than being added.
3. **Evidence that the contract holds two kinds.** With only collectors written, the
   contract could quietly take a collector's shape and nobody would find out until a
   normalizer was attempted. This is cheap insurance against that.

**What these rules deliberately are not.** Every transformation below is structural:
trim whitespace, fold keys to lower case, drop empty values, sort. None of them
decides what a field *means*. That boundary is not stylistic — `OQ-002` blocks the
design of a concrete normalizer until a provisional decision consumer, output unit,
evidence requirement, and human-review boundary are accepted, and picking rules that
interpret a field would answer that question by implication. `rule-baseline@0.1` is
the add-on that gets to do that, in B3, after OQ-002 resolves.

**Determinism is the property under test.** OQ-003 requires the same snapshot to
produce byte-identical output after canonical serialization, and that is testable
against rules this trivial — which is the point. Nothing here reads a clock, a random
source, or anything outside `config` and the snapshot, and `NormalizeContext` offers
none of those. Key order is fixed by sorting rather than left to input order, because
two snapshots holding the same record with differently ordered keys must still
produce one result.
"""

from __future__ import annotations

import json
from typing import Any

from addon_api.context import NormalizeContext
from addon_api.errors import AddonOutputInvalid, AddonPermanent
from addon_api.results import NormalizedResult, NormalizeOutcome

#: What `[addon].output_contract_version` in the manifest promises. Not Schema 0.x:
#: that is OQ-003's to define against real records, and this add-on exists partly to
#: exercise the machinery that will carry it.
OUTPUT_CONTRACT_VERSION = "0.1"


def run(context: NormalizeContext) -> NormalizeOutcome:
    """Fold each snapshot item into one structurally normalized record.

    `strict` makes an unparseable item a permanent failure instead of a skip. Both
    behaviours are needed by the conformance suite: skipping is the ordinary case, and
    the failure path is what proves an add-on's refusal reaches the platform as a
    non-retryable failure rather than as a silent zero.

    `fail_output` makes this add-on emit a result the output contract rejects. It
    exists so the suite can exercise `AddonOutputInvalid` against something real; an
    add-on with no way to produce bad output cannot demonstrate that bad output is
    caught.
    """
    strict = bool(context.config_field("strict", False))
    fail_output = bool(context.config_field("fail_output", False))

    results: list[NormalizedResult] = []
    skipped = 0

    for item in context.read_snapshot():
        try:
            text = item.payload.decode("utf-8")
        except UnicodeDecodeError as error:
            # Not a skip even when lenient: a snapshot is sealed and hash-verified, so
            # bytes that are not text are a defect in what was sealed rather than one
            # bad record among many.
            raise AddonPermanent(
                f"{item.item_key} is not valid utf-8", {"item_key": item.item_key}
            ) from error

        try:
            record = json.loads(text)
        except json.JSONDecodeError as error:
            if strict:
                raise AddonPermanent(
                    f"{item.item_key} is not valid JSON", {"item_key": item.item_key}
                ) from error
            skipped += 1
            continue

        if not isinstance(record, dict):
            if strict:
                raise AddonPermanent(
                    f"{item.item_key} is not a JSON object", {"item_key": item.item_key}
                )
            skipped += 1
            continue

        body = _fold(record)
        if fail_output:
            # A body the output contract cannot accept. Deliberately not a plausible
            # near-miss: the suite is checking that validation runs at all.
            body = {"": None}
        if not body:
            skipped += 1
            continue

        results.append(
            NormalizedResult(
                source_item_key=item.item_key,
                body=body,
                notes={"output_contract_version": OUTPUT_CONTRACT_VERSION},
            )
        )

    context.emit_result(results)
    context.log(
        "normalize.snapshot_read",
        {"emitted": len(results), "skipped": skipped, "strict": strict},
    )
    if fail_output and not results:
        raise AddonOutputInvalid(
            "fail_output was requested but the snapshot produced nothing to spoil",
            {"snapshot_id": context.snapshot_id},
        )
    return NormalizeOutcome(results_emitted=len(results), skipped=skipped)


def _fold(record: dict[str, Any]) -> dict[str, Any]:
    """Structure only: lower-case keys, trimmed strings, empties dropped, sorted.

    Sorted because determinism is the property being demonstrated and Python's dict
    preserves insertion order — two snapshots holding the same record with keys in
    different orders would otherwise serialize differently and fail a byte-for-byte
    comparison that ought to pass.

    `False` and `0` are kept while `None` and `""` are dropped, which is the one
    judgement in this function: an absent value and a value that happens to be falsey
    are different facts, and conflating them would be an interpretation rather than a
    structural change.
    """
    folded: dict[str, Any] = {}
    for key, value in record.items():
        name = str(key).strip().lower()
        if not name:
            continue
        if isinstance(value, str):
            value = value.strip()
            if not value:
                continue
        elif value is None:
            continue
        folded[name] = value
    return {name: folded[name] for name in sorted(folded)}
